text = input()
text = text.lstrip('*')
text = text.lstrip('_')
text = text.lstrip('~')
text = text.lstrip('`')
text = text.strip()
text = text.rstrip('*')
text = text.rstrip('_')
text = text.rstrip('~')
text = text.rstrip('`')
print(text)
